# development:
#   default:
#     adapter: mysql
#     database: mack-user_auth_portlet_development
#     host: localhost
#     username: root
#     password: 
#     
# test:
#   default:
#     adapter: mysql
#     database: mack-user_auth_portlet_test
#     host: localhost
#     username: root
#     password:
# 
# production:
#   default:
#     adapter: mysql
#     database: mack-user_auth_portlet_production
#     host: localhost
#     username: root
#     password:

# development:
#   default:
#     adapter: postgres
#     database: mack-user_auth_portlet_development
#     host: localhost
#     username: root
#     password: 
#     
# test:
#   default:
#     adapter: postgres
#     database: mack-user_auth_portlet_test
#     host: localhost
#     username: root
#     password:
# 
# production:
#   default:
#     adapter: postgres
#     database: mack-user_auth_portlet_production
#     host: localhost
#     username: root
#     password:

development:
  default:
    adapter: sqlite3
    database: <%= Mack::Paths.db("mack-user_auth_portlet_development.db") %>
 
test:
  default:
    adapter: sqlite3
    database: <%= Mack::Paths.db("mack-user_auth_portlet_test.db") %>
 
production:
  default:
    adapter: sqlite3
    database: <%= Mack::Paths.db("mack-user_auth_portlet_production.db") %>

